name: locika_dbn_test
description: Chat application for Centrum LOCIKA.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+23

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^11.1.4
  flutter_native_splash: ^2.2.12
  flutter_svg: ^2.0.7
  logging: ^1.1.0
  convex_bottom_bar: ^3.1.0+1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  package_info_plus: ^4.2.0
  provider: ^6.0.5
  settings_ui: ^2.0.2
  image: ^4.1.3
  lottie: ^2.2.0
  html: ^0.15.1
  http: ^1.1.0
  flutter_markdown: ^0.6.13+1
  chat_bubbles: ^1.4.1
  intl: ^0.18.0
  video_player: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  flutter_phone_direct_caller: ^2.1.1
  connectivity_plus: ^5.0.1
  flutter_email_sender: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dbn_icon.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/slider/
    - assets/texts/
    - assets/animations/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter/static/Bitter-Regular.ttf
        - asset: assets/fonts/Bitter/static/Bitter-Italic.ttf
          style: italic
        - asset: assets/fonts/Bitter/static/Bitter-Bold.ttf
          weight: 700
